### PR TITLE
Three Commits

### PR DESCRIPTION
**Pull request by wilsnat**
Hi, I love your toolset and I have three commits for your MyBox repository. I think the most useful one is the change to ConditionalFieldAttribute to allow for a second tag to be accepted. For example, this allows

```
[ConditionalField("someBool")]
[MinMaxRange(0,360)]
public float degrees;
```

to display properly. I commented the code a bit so you can understand the reflections (which suck to work with.)

Other than that, I added a browse asset function, useful for setting a folder if you want to instantiate a bunch of prefabs and changed the RangedInt/Float from structs to classes so they can be instantiated statically. Let me know if you have any questions.

-Nate

### CODE REVIEW

**Comment by Deadcows** [comment]
BrowseAssetsAttribute is perfect! I imagine how this might be helpful for editor tools and such :) 
Though I might imagine how it may be a type instead of attribute. Now it works only with strings anyway so it might be some string wrapper with custom inspector and extension functions maybe 🙄

**Comment by Deadcows** [comment]
BrowseAssetsAttribute is perfect! I imagine how this might be helpful for editor tools and such 😀
I remember how I put this path strings by hand a few times...
Though I might imagine how it may be a type instead of attribute. Now it works only with strings anyway so it might be some string wrapper with custom inspector and extension functions maybe 🙄

**Comment by Deadcows** [comment]
I'm not following on why to make ranged types classes instead of structs? I't good point to add constructors, totally forgot about this 😁 This will work fine: 

	[Serializable]
	public struct RangedFloat
	{
		public float Min;
		public float Max;

		public RangedFloat(float min, float max)
		{
			Min = min;
			Max = max;
		}
	}

`public RangedFloat test = new RangedFloat(1, 7);`

Or maybe there is some other reason to use classes in this case?

**Comment by Deadcows** [comment]
Got some strange results with new version of ConditionalField 🤔


	public bool someBool;
	[ConditionalField("someBool")] [MinMaxRange(0,360)] public float degrees;

	public int first;
	[ConditionalField(nameof(first), false, 1, 2, 3)] [Separator] public bool firstV;
		
	public int second;
	[ConditionalField(nameof(second), true, 1, 2, 3)] [Tooltip("So")] public bool secondV;

image

Oh now I tried with the old version, apparently both versions provide the same result.
I've got a bunch of log messages by the way, on cases with Separator and Tooltip:

image

**Comment by Deadcows** [comment]
Oooh and I remembered that MinMaxRangeAttribute only works with RangedInt or RangedFloat so with your example it won't work anyway 🙄
As far as I remember the problem is with multiple PropertyDrawers. 
In your example ConditionalAttribute PropertyDrawer and RangedInt PropertyDrawer are trying to draw the same property which is not possible afaik. BUT I just found [this thread ](https://forum.unity.com/threads/drawing-a-field-using-multiple-property-drawers.479377/) so maybe there is a hope :) Didn't read it yet though 😁

**Comment by kilik128** [comment]
same here somethink's happen with update use 

    public SubstanceGraph.InputPropertiesType typ;

    [ConditionalField("typ", SubstanceGraph.InputPropertiesType.Boolean)]
    public bool bole;


not working any more 

Assets\SubtanceAnimationLink\ProSub.cs(45,30): error CS1503: Argument 2: cannot convert from 'Substance.Game.SubstanceGraph.InputPropertiesType' to 'bool'

**Comment by wilsnat** [comment]
I think I know what the error is caused by (I think it always calls the default constructor even if I have arguments available.) I'll update it and see if that fixes it.

(BrowseAssets was initially built off of your Browse Buttons from MyGUI. I imagine that making it a custom class would probably be the right thing to do. Also, you were right about the RangedInt structs, I just wanted a constructor for RangedInt but forgot that you can do that for structs so my first reaction was a class. 😁)

**Comment by wilsnat** [comment]
Ok. I know exactly what is happening. SeperatorAttribute uses decorator drawers which I don't take into account and MinMaxRangeAttribute uses typed drawers, not based on the MinMaxRangeAttribute. I've tested this on a number of other attributes and it works.

My previous (and incorrect) example should have been:
```
public bool someBool;
[ConditionalField("someBool"), Range(0,360)]
public float degrees;
```
I'll try to extend the functionality to Decorator Drawers and refactor the MinMaxRange to be attribute driven and not type driven.

**Comment by wilsnat** [comment]
Holy crap. This is getting deeper than I thought. Took me a while to properly unpack arguments for the Attributes from Reflections, before it couldn't handle param arrays like in DefinedValuesAttribute but it can now. I'm going to go through each attribute and test it out. It also looks like I can't do decorator drawers as they get called separately from field attributes.

I'll let you know when I'm done. I'm using this for my own work anyways.

**Comment by wilsnat** [comment]
It is working for me. Let me know if this is closer to a usable state.

Collapsed:
ConditionalFieldCollapsed
Expanded:
ConditionalFieldExpanded

Note: The inline button class is not the one from the MyBox repository but if you were interested I could submit a separate pull request.

**Comment by Deadcows** [comment]
Incredible work! There is stuff to learn from your changes.
I made a few slight changes, can you please check my latest commit?
I messed up your tabulation with my default setup, sorry :)

I changed the way logging works, now warning will be shown only once. 
And also cached stuff where you grab all Types in the assembly. 
And wrapped "using UnityEditor;" in ifdef. 
So not much of a change, but I'd like you to check just in case :)

**Comment by Deadcows** [comment]
Made AssetPath and AssetFolderPath types out of BrowseAttribute:

    public AssetPath P1;
    public AssetPath P2 = AssetPath.WithExtension("asset");
    public AssetFolderPath P3;

**Comment by Deadcows** [comment]
New version of MinMaxRangeAttribute is not working for me. I'll check it further.

**Comment by Deadcows** [comment]
Well actually.... I thought why not to delete RangedInt/Float completely? We've got MinMaxInt/Float types already and for ranged inspector we may use MinMaxRange attribute 🙄

**Comment by Deadcows** [comment]
Oh that's was easy to fix :) Pesky bug this one

image

**Comment by Deadcows** [comment]
Yeah, I guess its time to merge :) 
I fixed this issue with MinMaxRangeAttribute and I also like your way to use single drawer for attribute instead of drawers for separate types (I don't remember why I decided to go this way with two drawers anyway 😄). With this approach it's possible to use MinMaxRange on Ranged type and also on MinMax type (and on any type with Min and Max int or float fields actually 🙂)

I slightly changed MinMaxRangeAttribute  to reduce code duplication and also came out with idea (WarningsPool) to log one warning at a time instead of spamming console. And used this one to add a few warnings if MinMaxRangeAttribute used on wrong type.

Thanks for your work!

**Comment by wilsnat** [comment]
Sorry, I was AFK this weekend. I'll sync my fork and play with your changes. Thanks for the work!

**Pull request merged**
