### PR TITLE
Remove dependencies to Unity Physics and AI Modules and cover them by defines

### PR DESCRIPTION
**Pull request by r1noff**
I just started new project, where I don't need physics at all. But MyBox has hard dependency on this modules. So I broke that coupling by using asmdef Version Defines feature.

### CODE REVIEW

**Comment by Deadcows** [comment]
Thanks! I never thought of that 🙂
The way you wrapper up some parts of ColliderGizmio type bring me to thought that I should refactor this thing 😁

Also, seemingly [you did add imageconversion dependency](https://github.com/Deadcows/MyBox/pull/197/commits/d9f9de0b49c272fec0be23978fe90490babce8b2) by mistake?

**Comment by Deadcows** [comment]
Иван, спасибо за помощь! 🙂

**Comment by r1noff** [comment]
Пожалуйста) imageconversion нужен для ImageStringConverter.cs

**Comment by r1noff** [comment]
LoadImage метод расширения из этого пакета используется в ImageStringConverter.cs
Если отключить пакет ImageConversion будет отшибка Library\PackageCache\com.domybest.mybox@35c756db20\Tools\ImageStringConverter\ImageStringConverter.cs(15,12): error CS1061: 'Texture2D' does not contain a definition for 'LoadImage' and no accessible extension method 'LoadImage' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)

**Comment by Deadcows** [comment]
Пофиксил, спасибо 👍🏻

**Pull request merged**
