### PR TITLE
Added MinMaxAttribute, Like MinMaxRange but Range is not needed.

### PR DESCRIPTION
**Pull request by Kaynn-Cahya**
```
    [MinMax]
    public MinMaxFloat minMaxFloatWithoutTheRange;

    [MinMax]
    public MinMaxInt minMaxIntWithoutTheRange;
```
[Gif of the attribute in action](https://i.imgur.com/jTgbPDW.gifv)

Basically its like `MinMaxRangeAttribute`, but the values you can input are not bound by a range.

### CODE REVIEW

**Comment by Deadcows** [comment]
Cool idea 😀 As always!😉 

I noticed that you actually don't use MinMaxAttribute 😬 
The work lays totally on MinMax custom property drawer. 
So I moved MinMax types to Types folder. It's a good place to be, along with OptionalMinMax type.

Also I decided to disable warnings if values are equal. 
This case might be a valid behavior + it spammed warnings if nothing is assigned (this case might be handled with [MustBeAssigned])

And then I realized that I've got nice drawer for OptionalMinMax and adjusted it do draw MinMax, so it's almost no code left from your side 🙊. I hope it's fine with you

**Comment by Kaynn-Cahya** [comment]
@Deadcows  

> And then I realized that I've got nice drawer for OptionalMinMax and adjusted it do draw MinMax, so it's almost no code left from your side 🙊. I hope it's fine with you

Yea that is fine, since I often annoyed by the fact that I needed to always include a range for `MinMax` attribute.
(There are some situations where I don't really needed the range, but I just wanted a MinMax)

**Comment by Deadcows** [comment]
[Commit with this changes](https://github.com/Deadcows/MyBox/commit/20d3693c43a562d42c1b70623562d40fbaa899fc) and [usage example](https://github.com/Deadcows/MyBox/wiki/Types#minmaxint-and-minmaxfloat)

**Comment by Deadcows** [comment]
Cool! So as you use MinMax already, please let me know if you'll find MinMax inspector somewhat awkward to use 🤠

**Pull request merged**
