### PR TITLE
Add AllowEmpty to AutoProperty

### PR DESCRIPTION
**Pull request by YogurtTheHorse**
This would allow to have empty\null values for auto properties if developer wants to

### CODE REVIEW

**Comment by Deadcows** [comment]
Oh dang, I wondered why all my commits are missing! I did messed up 😁

**Comment by yezh-trackman** [comment]
Oooh. Yeah...

**Comment by YogurtTheHorse** [comment]
Oof. Yeah…

**Comment by Deadcows** [comment]
Can you please create another PR? I'm not sure how to fix my mess now. 
I could just copypaste the change, but I don't want to discard you from the contributors list 🤔

**Comment by YogurtTheHorse** [comment]
Should fine now :)

**Comment by Deadcows** [comment]
git ninja, I appreciate it 🙌 I should learn it also 🤦‍♂️
Thank you for the contribution, really nice addition!

**Comment by YogurtTheHorse** [comment]
I just pressed big button “resolve conflicts” :D

**Comment by Deadcows** [comment]
You're not scared off by some big buttons, that's something 😁

**Pull request merged**
