### PR TITLE
[ConditionalField]

### PR DESCRIPTION
**Pull request by wilsnat**
Added the ability to work with types. I realized when you shifted the AssetPath to a type that I could no longer use it as intended. I added a new derivative function to handle types called GetTypeDrawerType(). You could probably extend the GetPropertyDrawerType to handle both types and attribtues but I just need to get it working asap. It should at least be working but feel free to clean it up.

### CODE REVIEW

**Comment by wilsnat** [comment]
Woah woah woah. That won't work. I was creating an instance of the object instead of getting the object. Let me see if I can figure this out.

**Comment by wilsnat** [comment]
Sorry about that. Seems to be working now.

**Comment by Deadcows** [comment]
Why do you was unable to use AssetPath? Maybe there is something to make it viable? I'll check your work tomorrow :)

**Comment by wilsnat** [comment]
It was because you changed AssetPath to a type. I had only built in support for Attributes. The fix was to extend the search to compare against Types, remove the reflection of Attribute arguments and remove the instantiation of a new object (because we really just wanted fieldInfo, not a new object of type fieldInfo.FieldType.) This also means it will work with other types like MinMaxInt now.

**Comment by Deadcows** [comment]
I thought it's not possible to use custom drawer inside of another drawer. Incredible work, there is much to learn 🤓!

I commented out warning for block with comment "Reassign the attribute field in the drawer so it can access the argument values". It was hit by types with CustomPropertyDrawer.

**Comment by Deadcows** [comment]
Yet it's still not working with Types where CustomPropertyDrawer is on base class, like OptionalComponent or UnityEvent 🙄 But I guess if I'll take time to dig into your solution I'll manage to solve this

**Comment by wilsnat** [comment]
It also still doesn't work with arrays but after looking at [PropertyHandler](https://github.com/Unity-Technologies/UnityCsReference/blob/02d565cf3dd0f6b15069ba976064c75dc2705b08/Editor/Mono/ScriptAttributeGUI/PropertyHandler.cs), I'm not sure it would ever work on the full array. It just hands the attribute to the individual elements. I did try to get it working on at least those elements of the array (which you can set an array of strings to display as the AssetPath Attribute) but I couldn't get it to update properly with the conditional.

**Comment by wilsnat** [comment]
And as for the two you mentioned, it looks like the main issue with those is that they are searching for the child class in the CustomPropertyDrawers when in reality it is the parent class you want. You could set those as specific exceptions or you could do a recursive search to see if the parent class has a CustomPropertyDrawer. And for some reason I thought UnityEvents were more complex than that but maybe it as simple as looking for UnityEventBase instead of the child UnityEvent classes.

**Comment by Deadcows** [comment]
Yep, with arrays I believe it is possible to make custom inspector for every MonoBehaviour and draw everything just like in the regular inspector but cut out Conditional things 🙄

**Pull request merged**
